# Generated by Django 4.2.2 on 2023-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('phone', models.TextField()),
            ],
        ),
    ]
