# Generated by Django 4.2.2 on 2023-06-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='last_contact',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='phone',
            field=models.TextField(blank=True, verbose_name='phone number'),
        ),
    ]
