# Generated by Django 4.2.2 on 2023-07-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0002_friend_last_contact_alter_friend_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
