# Generated by Django 4.2.2 on 2023-07-14 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hey.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hey', '0002_friend_pronouns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.SmallIntegerField(validators=[hey.models.validate_tz_offset])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
