# Generated by Django 4.2.2 on 2023-07-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0005_friend_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='unit',
            field=models.TextField(choices=[('D', 'day'), ('W', 'week'), ('M', 'month')], default='W', max_length=1),
        ),
    ]
